# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
locale: "ja-JP"

title: "RTK Revision"
subtitle: "Personal site to help revise RTK"

repository: ificiana/null
breadcrumbs: false
search: true
# search_provider: algolia
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

description: >- # this means to ignore newlines until "baseurl:"
  Personal site to help revise RTK
url: https://ificiana.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /rtk/

plugins:
  - jekyll-include-cache
  - jekyll-pwa-plugin

# pwa configs
pwa:
  enabled: true # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

author:
  name: "Arkaprabha Sinha-Roy"
  avatar: "https://github.com/ificiana.png"
  bio: "I am an **amazing** person." # Note: Markdown is allowed
  location: "Somewhere"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ificiana"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ificiana"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ificiana"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ificiana"

exclude:
  - .git
  - .bundle
  - .idea
  - Gemfile
  - Gemfile.lock
  - _config.yml
  - _layouts
  - params.json
  - vendor
  - bot
  - heisig-kanjis
  